# Versão do Docker Compose
version: '3.8'

# Aqui definimos todos os containers (chamados de 'serviços')
services:

  # Serviço 1: O Banco de Dados PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      # As variáveis são lidas do arquivo .env
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Serviço 2: A sua aplicação Go
  app:
    build: .
    image: myapp:latest
    container_name: go_app
    restart: always
    ports:
      - "8080:8080" # Mantenha se sua app for um servidor web
    depends_on:
      - db
    environment:
      # Passa as mesmas variáveis para a sua aplicação Go
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}

# Define os 'volumes' para persistência de dados
volumes:
  postgres-data: